version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always
    environment:
      - RELAY_HOST=smtp.sendgrid.net
      - RELAY_PORT=587
      - RELAY_USERNAME=apikey
    env_file:
      # In the file, put the following value: RELAY_PASSWORD=secretpassword
      - ./apikey_sendgrid.env

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - internal

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    networks:
      - internal
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    env_file:
      - plausible-conf.env
    networks:
      - default
      - internal
    labels:
      - "traefik.http.routers.plausible.rule=Host(`URL`)"
      - "traefik.http.routers.plausible.entrypoints=websecure"
      - "traefik.http.routers.plausible.tls.certresolver=myresolver"

networks:
    internal:
    default:
        external:
            name: gateway
volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
